version: '2'

services:
  mongo:
    image: mongo:3.7.2
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db

  backend_image:
    image: backend_image
    build:
      context: .
      dockerfile: ./backend.dockerfile
    links:
      - mongo
    depends_on:
      - mongo

  app:
    image: backend_image
    volumes:
      - "./src/squeal_bot:./var/www/"
    command: bash -c "python /var/www/__main__.py"
